export enum DeviceType {
  LIGHT = "LIGHT",
  FAN = "FAN",
  CAMERA = "CAMERA",
  HUMIDTY_SENSOR = "HUMIDTY_SENSOR",
  TEMPERATURE_SENSOR = "TEMPERATURE_SENSOR",
  ELECTRIC_METER = "ELECTRIC_METER",
  WATER_METER = "WATER_METER",
}